CREATE TABLE IF NOT EXISTS images (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  uploaded_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS hotspots (
  id SERIAL PRIMARY KEY,
  image_id INT NOT NULL REFERENCES images(id) ON DELETE CASCADE,
  x FLOAT NOT NULL,
  y FLOAT NOT NULL,
  width FLOAT NOT NULL,
  height FLOAT NOT NULL,
  target_image_id INT REFERENCES images(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS demo_versions (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS demo_version_images (
  id SERIAL PRIMARY KEY,
  demo_version_id INT NOT NULL REFERENCES demo_versions(id) ON DELETE CASCADE,
  image_id INT NOT NULL REFERENCES images(id) ON DELETE CASCADE
);
